### PR TITLE
Bring MacOS/Windows back into CI

### PR DESCRIPTION
**Pull request by WhiffleFish**

### CODE REVIEW

**Comment by zsunberg** [comment]
*sigh* now we have to make all of our gh actions scripts windows-proof. Yet another man-hour of humanity's time that Microsoft has wasted.

**Comment by zsunberg** [comment]
@WhiffleFish this is amazing. Can you add a comment to the yml file explaining that the conversion of symbols to strings is to maintain OS compatibility?

**Comment by lassepe** [comment]
I understand why we need `joinpath` but I don't understand why we need to convert Symbols to string instead of using literal strings directly? For example, isn't `string(:lib) === "lib"` irrespective of the OS?

**Comment by mykelk** [comment]
Maybe because it is in a quoted shell command?

**Comment by zsunberg** [comment]
I assume that it has to do with the way windows handles various quotes, so you can't use the trick where ' are used to create arguments with " in them. Thus, we have to avoid using " anywhere in the command.

@WhiffleFish is this correct? Can you add the comment requested above so that I can merge this?

**Comment by WhiffleFish** [comment]
Yep, Mykel is entirely correct. I figured there'd be a way to escape the quotes (`\"`) in a way that would work across operating systems, but haven't been able to find a way to do so.

**Comment by zsunberg** [comment]
@WhiffleFish thanks! It seems like there should be a recommended way that is more straightforward, but this is great for now.

**Pull request merged**
