### PR TITLE
adding AEMS to list of solvers

### PR DESCRIPTION
**Pull request by dressel**
The AEMS solver is ready for a first release. There are some minor cosmetic issues and I may make small changes in the coming days but most of the major stuff is done.

@zsunberg can you please the add coverall stuff (by pressing the buttons on the AEMS readme)? It won't let me because I apparently am a second-class citizen in this group.

As I mention in the documentation for AEMS, I think we should have an `update(policy, a, o)` function or pass in the action+observation to the `action` function. With a tree based solver, having these allows you to save the tree and move the root of the tree. You could search the tree for beliefs matching the current belief in order to set the node, but that's messy and possibly grossly inefficient. Giving the observation to the planner (or passing it into `action`) would also allow you easily build a planner that only depends on the previous observation (which you might want as a baseline).

### CODE REVIEW

**Comment by mykelk** [comment]
I added you as an owner. You might also have to make your membership public so that travis and coveralls recognizes you. In any case, I turned on the build and coverage analysis for this package.

**Comment by zsunberg** [comment]
> I think we should have an update(policy, a, o) function or pass in the action+observation to the action function.

I originally tried to re-use parts of the tree with POMCP, but then abandoned it. There are two things to consider here:

1. The main reason I abandoned this with POMCP is that re-using the tree wasn't actually that useful in practice. Say there are 5 actions and 5 observations, then the sub-tree that you can re-use on the next step is typically only 1/25 of the original tree, so it's not that bad to just start over with a new tree.

2. You can accomplish tree re-use in the current interface by making the belief a tree node, and the updater just traverses the tree when it gets an action and observation.

Happy to discuss this more. If you want to continue, open a separate issue.

**Comment by mykelk** [comment]
Yeah, in practice, tree reuse doesn't save you much.

**Comment by dressel** [comment]
> Say there are 5 actions and 5 observations, then the sub-tree that you can re-use on the next step is typically only 1/25 of the original tree, so it's not that bad to just start over with a new tree.

That assumes you've explored the tree fairly uniformly. However, the goal in tree-based methods is to only expand in promising directions, so the bulk of your tree should actually be concentrated in actions you will likely take. In the original AEMS paper, they reused about 33% of the tree even when |A| = 13 and |O| = 2, instead of the 1/26 th that you reasoning would expect.

I don't know that saving the tree will be always be useful, but I think applying the same logic from sampling-based tree methods does not necessarily apply to scenarios where you are more selective with the nodes expanded.

**Comment by zsunberg** [comment]
Right - POMCP also explores the action it actually takes more often, so 1/25 is on the lower end of the actual re-use you would encounter, but I would argue that even 33% re-use is not that important.

Anyways, there are multiple ways to accomplish tree re-use without changing the interface by using a special updater (which could use any arbitrary updater within it), so I think we should pursue that rather than change the interface.

**Pull request merged**
