### PR TITLE
fixed typos. 

### PR DESCRIPTION
**Pull request by MaderDash**
This should address the typos mentioned in issue #554. #554

### CODE REVIEW

**Review by zsunberg — CHANGES_REQUESTED** [review]
Thanks @MaderDash ! this is really helpful, but it looks like a bunch of new files were added by mistake (i.e. everything in the .history folder). Can you remove those?

**Comment by MaderDash** [comment]
Not a problem, please see if this will correct it.

**Comment by dylan-asmar** [comment]
The changes look good to me. Since the PR is not from the JuliaPOMDP/POMDPs.jl repo, it didn't generate a preview for the docs. However, I think the issue with the linter only showing the boolean remains ([this section](https://juliapomdp.github.io/POMDPs.jl/stable/example_gridworld_mdp/#Grid-World-Remaining-Functions)). I think we can add a hidden `nothing` expression to have it return the `stdout` stream in accordance with the `@example` [documentation](https://documenter.juliadocs.org/stable/man/syntax/#reference-at-example).

**Review by zsunberg — APPROVED** [review]
Thanks for removing the extra files. LGTM whenever @dylan-asmar is ready

**Comment by zsunberg** [comment]
@dylan-asmar can you merge this when you're ready?

**Pull request merged**
