### PR TITLE
adding FIB to native package list

### PR DESCRIPTION
**Pull request by dressel**

### CODE REVIEW

**Comment by zsunberg** [comment]
Thanks for the contribution!

I added a couple issues to the FIB package to fix before we merge this. Also, please add FIB to the list of packages in the README.

Note, since you are a member of the JuliaPOMDP group, you don't need to fork the package to your own repository under github.com/dressel. Instead, you can just make a branch with git and push that to the POMDPs.jl repo at github.com/JuliaPOMDP/POMDPs.jl and then create a PR from that. You can do it however you like, I just find the latter way easier.

**Comment by zsunberg** [comment]
Also that way anyone from JuliaPOMDP can make changes to the PR, which might make things easier.

**Comment by dressel** [comment]
FIB now has Travis and coveralls. I've modified the pull request to include FIB in the readme and documentation.

In the future, I'll simply branch as you suggest above.

**Comment by mykelk** [comment]
It looks like there is something going wrong with the Apple build. It is having trouble with Rmath.

**Comment by dressel** [comment]
That's kind of bizarre. I don't think any of my changes would have affected that...

**Comment by mykelk** [comment]
You can probably just turn off the Apple build in the yml file.

**Comment by dressel** [comment]
We could, but does this mean people using Apple computers are likely to run into errors when using POMDPs?

**Comment by mykelk** [comment]
Maybe. I just restarted the Apple job since it looks like Rmath.jl builds fine. There may have just been a hiccup.

**Comment by dressel** [comment]
Yeah it now looks like everything has passed. Guess it was a hiccup.

**Comment by zsunberg** [comment]
Great, Thanks @dressel ! It looks good to me now.

Yeah, I'd say about 10% of the time Rmath fails to build on mac OS. I just restart it whenever it does.

**Comment by zsunberg** [comment]
I merged it into master, but it is *not* in a tagged release yet. I noticed you're working on AEMS. Should I tag a release now, or wait until you're done with that?

**Comment by dressel** [comment]
Although AEMS technically works, it's still a bit rough and missing documentation and some functionality that I'd like to put in there. I'll probably be making changes to it over the next couple weeks. It's up to you if you want to tag now.

**Comment by zsunberg** [comment]
We'll wait. No huge rush.

**Pull request merged**
